#!/usr/bin/env bash

alias cp='cp -i'
alias tree='tree -a'
alias ls='ls --color=auto -a'
alias rm='rm -I'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias open='xdg-open'
if [ $(command -v doas) ]; then
    alias sudo='doas'
fi

alias wget=wget --hsts-file="$XDG_DATA_HOME"/wget-hsts
alias yarn=yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config
