#!/usr/bin/env bash

export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

export CARGO_HOME="$XDG_DATA_HOME"/cargo

export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

export KDEHOME="$XDG_CONFIG_HOME"/kde

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

export NVM_DIR="$XDG_DATA_HOME"/nvm

export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

export WINEPREFIX="$XDG_DATA_HOME"/wine

#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export ANDROID_SDK_ROOT="$XDG_DATA_HOME"/android
export ANDROID_SDK_HOME="$XDG_DATA_HOME"/android
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android

export VCPKG_ROOT="$XDG_DATA_HOME"/vcpkg

export LESSHISTFILE="$XDG_DATA_HOME"/less/history

export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
