#!/usr/bin/env bash

if ! command -v xfreerdp &> /dev/null
then
    echo "This script requires xfreerdp to be installed."
    exit
fi

got_host=0
got_user=0
multimon=0
quality=0

while getopts h:u:mq opt; do
    case $opt in
        h ) got_host=1;host=$OPTARG ;;
        u ) got_user=1;user=$OPTARG ;;
        m ) multimon=1              ;;
        q ) quality=1               ;;
        ? ) exit                    ;;
        : ) exit                    ;;
    esac
done

if [[ ! got_host -eq 1 ]]; then
    echo "Host is required"
    exit
fi

if [[ ! got_user -eq 1 ]]; then
    echo "Username is required"
    exit
fi

multimon_flag=""
if [[ $multimon -eq 1 ]]; then
    multimon_flag="/multimon"
fi

quality_flags=""
if [[ $quality -eq 1 ]]; then
    quality_flags="+aero +window-drag"
fi

xfreerdp /v:$host /u:$user $multimon_flag $quality_flags
